version: '3.8'
services:
  db:
    image: mysql:8
    container_name: af-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ilham123
      MYSQL_DATABASE: coaching_financier
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    name: af-mysql-data
